# Site settings
title: Codingarena
email: neo@codingarene.in
description: "I'm a programmer from the Venice of the East, the very own Gods own country, Kerala, India who codes Ruby, Golang, Elixir and JS for a living, hacks for fun and learns for passion."
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://codingarena.in" # the base hostname & protocol for your site
twitter_username: manusajith
github_username:  manusajith

name: 'Manu S Ajith'
author: 'Manu S Ajith'
author_image: "/blog/assets/images/manu.png"
author_bio: " #programmer, #hacker, #entrepreneur, open source evangelist. #Ruby, #Golang, #Elixir, #JS, Lazy #Blogger. Writes #code for a living."

# Build settings
markdown: kramdown
highlighter: pygments

permalink: /blog/:year/:month/:day/:title/
disqus: codingarenablog

gems:
  - octopress-image-tag
  - octopress-video-tag
  - octopress-codeblock
  - octopress-quote-tag
  - octopress-codefence
  - octopress-solarized
  - octopress-gist

#blog logo
logo: "/blog/assets/images/manu.png"
# blog cover
cover: "/blog/assets/images/bg.jpg"

paginate:	5

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/manusajith
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/manusajith
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
